name: Scheduled testRigor Run

on:
  schedule:
    # Runs at 9:00 AM UTC daily — adjust as needed
    - cron: '10 22 * * *'

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Call testRigor API
        run: |
          curl -X POST  https://api.testrigor.com/api/v1/apps/G8JtRJgB36w4tH52h/retest \
           -H 'Content-type: application/json' \
            -H 'auth-token: 8081e097-7f84-4157-901d-26bb13718795' \
            --data '{ "labels": [ "test", ], "excludedLabels": [ "some-label", "other-label" ] }'
